# Generated by Django 3.0.8 on 2020-07-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('major', models.CharField(max_length=200)),
                ('semester', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('data', models.FileField(null=True, upload_to='./file')),
            ],
        ),
    ]
