# Generated by Django 3.0.8 on 2020-07-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='data',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
