# Generated by Django 3.0.8 on 2020-07-24 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_auto_20200724_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='owner',
            new_name='note',
        ),
    ]
