# Generated by Django 3.0.8 on 2020-07-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_auto_20200724_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_name',
        ),
        migrations.AlterField(
            model_name='file',
            name='major',
            field=models.CharField(help_text='줄임말이 아니라 정확히 입력', max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='note',
            field=models.CharField(help_text='설명란', max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='semester',
            field=models.CharField(help_text='0학년 0학기와 같이 입력', max_length=200),
        ),
    ]
