# Generated by Django 3.0.8 on 2020-07-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_auto_20200724_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='major',
        ),
        migrations.RemoveField(
            model_name='file',
            name='note',
        ),
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.CharField(default='', help_text='설명란', max_length=200),
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.CharField(default='', help_text='파일 주인 이름 입력', max_length=200),
        ),
        migrations.AddField(
            model_name='file',
            name='subject',
            field=models.CharField(default='', help_text='줄임말이 아니라 정확히 입력', max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='semester',
            field=models.CharField(default='', help_text='0학년 0학기와 같이 입력', max_length=200),
        ),
    ]
