# Generated by Django 3.0.8 on 2020-07-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_auto_20200724_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='major',
            field=models.CharField(choices=[('ece', '전기'), ('cse', '컴퓨터')], default='', max_length=20),
        ),
    ]
