# Generated by Django 3.0.8 on 2020-07-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0006_file_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='subject',
        ),
        migrations.AddField(
            model_name='file',
            name='note',
            field=models.CharField(default='', help_text='설명 입력 ex) 텀프 파일, 수업자료...', max_length=200),
        ),
    ]
