# Generated by Django 3.0.8 on 2020-07-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0008_auto_20200724_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='subject',
            field=models.CharField(default='', help_text='줄임말이 아닌 수업명 입력', max_length=200),
        ),
    ]
