# Generated by Django 3.0.8 on 2020-07-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0009_auto_20200724_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='major',
            field=models.CharField(choices=[('eec', '전자'), ('ece', '전기'), ('cse', '컴퓨터')], default='', max_length=20),
        ),
    ]
