# Generated by Django 3.0.8 on 2020-07-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='type',
            field=models.CharField(choices=[('user', '사용자'), ('admin', '관리자')], default='', max_length=20),
        ),
    ]
