# Generated by Django 3.0.8 on 2020-08-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_accounts_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='year',
            field=models.IntegerField(default='0000', help_text='입학년도를 4자리로 입력', max_length=4),
        ),
    ]
