# Generated by Django 3.0.8 on 2020-08-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200805_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='year',
            field=models.IntegerField(default=2020, help_text='입학년도를 4자리로 입력'),
        ),
    ]
