# Generated by Django 3.0.8 on 2020-07-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='file',
            field=models.FileField(null=True, upload_to='./file'),
        ),
    ]
