# Generated by Django 3.0.8 on 2020-07-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='./file')),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='file',
        ),
    ]
