# Generated by Django 3.0.8 on 2020-07-24 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200724_1524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
