# Generated by Django 3.0.8 on 2020-07-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200729_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='type_of_article',
            field=models.CharField(choices=[('notice', '공지사항'), ('blog', '게시글')], default='', max_length=20),
        ),
    ]
